version: '3'
services:
    keymanager-grpc:
      build:
        dockerfile: ./Dockerfile
        context: .
      ports:
      - 50051:50051
      depends_on:
        - postgres
        - bcb
        - erp-itau
      environment:
        DB_URL: jdbc:postgresql://postgres:5432/postgres
        DB_USER: postgres
        DB_PASS: postgres
        ERP_ITAU_URL: http://erp-itau:9091
        BCB_PIX_URL: http://bcb:8082
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
    postgres:
        image: 'postgres:alpine'
        volumes:
          - postgres-volume:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pix
          POSTGRES_HOST: postgres

volumes:
    postgres-volume: