micronaut:
  application:
    name: pixKeyManagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop